apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-message-parser-
  labels:
    app: parser
spec:
  #nodeName: testing-cluster-pool-b7x67
  containers:
  - name: parser
    image: lorenzobacchiani/parser
    env:
      - name: REDIS_HOST
        value: "redis-service"
      - name: MCL
        value: "110"

