apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-virus-scanner-
  labels:
    app: virus-scanner
spec:
  nodeName: testing-cluster-pool-b7x67
  containers:
  - name: virus-scanner
    image: giovaz94/virus-scanner-service:development
    env:
      - name: HOSTNAME
        value: "rabbitmq-service"
      - name: RABBITMQ_USERNAME
        value: "pipeline_broker"
      - name: RABBITMQ_PASSWORD
        value: "p1p3l1n3"
      - name: RABBITMQ_VHOST
        value: "pipeline-vhost"
      - name: QUEUE_NAME
        value: "virusscan.queue"
      - name: DB_URL
        value: "http://monitor-service:3200"
      - name: MCL
        value: "120"
      - name: PREFETCH
        value: "10"

   
    