apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-attachment-manager-
spec:
  containers:
  - name: attachment-manager
    image: giovaz94/attachment-manager-service:development
    resources:
      requests:
        cpu: 300m
        memory: 200M
  spec:
    nodeSelector:
      kubernetes.io/hostname: k3d-k3s-default-agent-2