apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-nsfw-detector-
  labels:
    app: nsfw-detector
spec:
  nodeName: testing-cluster-pool-b7x6c
  containers:
  - name: nsfw-detector
    image: lorenzobacchiani/nsfw-detector
    env:
      - name: REDIS_HOST
        value: "redis-service"
      - name: MCL
        value: "90"
      - name: LIMIT
        value: "400"
      - name: BATCH
        value: "90"