apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-message-analyzer-
  labels:
    app: message-analyzer
spec:
  #nodeName: testing-cluster-pool-b7x6u
  containers:
  - name: message-analyzer
    image: lorenzobacchiani/message-analyzer
    env:
      - name: REDIS_HOST
        value: "redis-service"
      - name: MCL
        value: "120"
      - name: LIMIT
        value: "500"