apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-attachment-manager-
  labels:
    app: attachment-manager
spec:
  #nodeName: testing-cluster-pool-b7x6u
  containers:
  - name: attachment-manager
    image: lorenzobacchiani/attachment-manager
    env:
      - name: MCL
        value: "231"
      - name: REDIS_HOST
        value: "redis-service"
      - name: LIMIT
        value: "400"
      - name: BATCH
        value: "231"

