apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-image-analyzer-
  labels:
    app: image-analyzer
spec:
  nodeName:  testing-cluster-pool-bnp17
  containers:
  - name: image-analyzer
    image: giovaz94/image-analyzer-service:development
    env:
      - name: HOSTNAME
        value: "rabbitmq-service"
      - name: RABBITMQ_USERNAME
        value: "pipeline_broker"
      - name: RABBITMQ_PASSWORD
        value: "p1p3l1n3"
      - name: RABBITMQ_VHOST
        value: "pipeline-vhost"
      - name: INPUT_QUEUE_NAME
        value: "imageanalyzer.queue"
      - name: OUTPUT_QUEUE_NAME
        value: "imageanalyzer.out.queue"
      - name: DB_URL
        value: "http://monitor-service:3200"
      - name: REDIS_HOST
        value: "redis-service"
      - name: MCL
        value: "231"
  