apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-image-analyzer-
  labels:
    app: image-analyzer
spec:
  #nodeName: testing-cluster-pool-b7x6u
  containers:
  - name: image-analyzer
    image: lorenzobacchiani/image-analyzer
    env:
      - name: REDIS_HOST
        value: "redis-service"
      - name: MCL
        value: "231"
      - name: LIMIT
        value: "200"
      - name: BATCH
        value: "231"

  