apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-nsfw-detector-
  labels:
    app: nsfw-detector
spec:
  nodeName: testing-cluster-pool-b7x6q
  containers:
  - name: nsfw-detector
    image: giovaz94/nsfw-detector-service:refactor-remove-rabbitmq
    env:
      - name: HOSTNAME
        value: "rabbitmq-service"
      - name: RABBITMQ_USERNAME
        value: "pipeline_broker"
      - name: RABBITMQ_PASSWORD
        value: "p1p3l1n3"
      - name: RABBITMQ_VHOST
        value: "pipeline-vhost"
      - name: QUEUE_NAME
        value: "nsfwdet.queue"
      - name: DB_URL
        value: "http://monitor-service:3200"
      - name: REDIS_HOST
        value: "redis-service"
      - name: MCL
        value: "90"
      - name: PREFETCH
        value: "0"