apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-message-analyzer-
  labels:
    app: message-analyzer
spec:
  nodeName: testing-cluster-pool-b7x6m
  containers:
  - name: message-analyzer
    image: giovaz94/message-analyzer-service:development
    env:
      - name: HOSTNAME
        value: "rabbitmq-service"
      - name: RABBITMQ_USERNAME
        value: "pipeline_broker"
      - name: RABBITMQ_PASSWORD
        value: "p1p3l1n3"
      - name: RABBITMQ_VHOST
        value: "pipeline-vhost"
      - name: QUEUE_NAME
        value: "messageanalyzer.queue"
      - name: DB_URL
        value: "http://monitor-service:3200"
      - name: REDIS_HOST
        value: "redis-service"
      - name: MCL
        value: "120"
      - name: PREFETCH
        value: "0"
