apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-virus-scanner-
  labels:
    app: virus-scanner
spec:
  #nodeName: testing-cluster-pool-b7x6y
  containers:
  - name: virus-scanner
    image: lorenzobacchiani/virus-scanner
    env:
      - name: MCL
        value: "120"
      - name: REDIS_HOST
        value: "redis-service"
      - name: LIMIT
        value: "200"
      - name: BATCH
        value: "120"
   
    