apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-nsfw-detector-
spec:
  nodeName: k3d-k3s-default-agent-1
  containers:
  - name: nsfw-detector
    image: giovaz94/nsfw-detector-service:development