apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-message-analyzer-
  labels:
    app: message-analyzer
spec:
  #nodeName: testing-cluster-pool-b7x6c
  containers:
  - name: message-analyzer
    image: lorenzobacchiani/message-analyzer
    env:
      - name: REDIS_HOST
        value: "redis-service"
      - name: MCL
        value: "300"
      - name: LIMIT
        value: "1000"
      - name: BATCH
        value: "300"