apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-virus-scanner-
spec:
  containers:
  - name: virus-scanner
    image: giovaz94/virus-scanner-service:development
    resources:
      requests:
        cpu: 300m
        memory: 200M
  spec:
    nodeSelector:
      kubernetes.io/hostname: k3d-k3s-default-agent-2