apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-message-analyzer-
  labels:
      app: message-analyzer
spec:
  nodeName: k3d-k3s-default-agent-1
  containers:
  - name: message-analyzer
    image: giovaz94/message-analyzer-service:development