apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-virus-scanner-
spec:
  nodeName: testing-cluster-pool-rjxyb
  containers:
  - name: virus-scanner
    image: giovaz94/virus-scanner-service:development
