apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-virus-scanner-
spec:
  nodeName: k3d-k3s-default-agent-0
  containers:
  - name: virus-scanner
    image: giovaz94/virus-scanner-service:development
