apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-attachment-manager-
spec:
  nodeName: testing-cluster-pool-rjxyb
  containers:
  - name: attachment-manager
    image: giovaz94/attachment-manager-service:development
 