apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-image-analyzer-
spec:
  nodeName: testing-cluster-pool-rjxyb
  containers:
  - name: image-analyzer
    image: giovaz94/image-analyzer-service:development
  