apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-image-analyzer-
spec:
  nodeName: k3d-k3s-default-agent-1
  containers:
  - name: image-analyzer
    image: giovaz94/image-analyzer-service:development
  