name: Test code

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create the test cluster
      uses: AbsaOSS/k3d-action@v2
      with:
        cluster-name: "k3s-default"
        args: >-
          -p "8010:80@agent:0"
          --agents 3
          --k3s-arg "--no-deploy=metrics-server@server:*"
    
    - name: Run tests with pytest
      run: pytest -s 
    